name: shared
resolution: workspace
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.10.0-162.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2
  vector_graphics: ^1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_graphics_compiler: ^1.1.19
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  transformers:
        - package: vector_graphics_compiler

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueLight.otf
        - asset: assets/fonts/HelveticaNeueMedium.otf
        - asset: assets/fonts/HelveticaNeueBold.otf
        - asset: assets/fonts/HelveticaNeueThin.otf