name: silent_moon_platform
publish_to: none

workspace:
- applications/mobile_application
- packages/silent_moon_kit

environment:
  sdk: '^3.10.0-162.1.beta'

scripts:
  format: melos exec -- flutter format
  clean: melos exec -- flutter clean
  get: melos exec -- flutter pub get
  analyze: melos exec -- flutter analyze
  create_package:
    run: melos exec -c 1 -- flutter create --template=package packages/${name}
