name: silent_moon_platform
publish_to: none

workspace:
- applications/mobile_application
- packages/shared

environment:
  sdk: '^3.10.0-162.1.beta'

melos:
  scripts:
    format: melos exec -- flutter format
    clean: melos exec -- flutter clean
    get: melos exec -- flutter pub get
    analyze: melos exec -- flutter analyze
    create_package:
      run: melos exec -c 1 -- flutter create --template=package packages/${name}
    generate:
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build
dev_dependencies:
  melos: ^7.3.0
