name: silent_moon_core
resolution: workspace
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.10.0-162.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueLight.otf
        - asset: assets/fonts/HelveticaNeueMedium.otf
        - asset: assets/fonts/HelveticaNeueBold.otf
        - asset: assets/fonts/HelveticaNeueThin.otf